ROTOR_IDENTITY = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
REFLECTOR_IDENTITY = ROTOR_IDENTITY  # not really possible!

ETW_ENIGMA1 = ROTOR_IDENTITY
ROTOR_ENIGMA1_1 = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
ROTOR_ENIGMA1_2 = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
ROTOR_ENIGMA1_3 = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
ROTOR_ENIGMA1_4 = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
ROTOR_ENIGMA1_5 = "VZBRGITYUPSDNHLXAWMJQOFECK"
REFLECTOR_ENIGMA1_UKW_A = "EJMZALYXVBWFCRQUONTSPIKHGD"
REFLECTOR_ENIGMA1_UKW_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
REFLECTOR_ENIGMA1_UKW_C = "FVPJIAOYEDRZXWGCTKUQSBNMHL"

ETW_ENIGMAM4 = ROTOR_IDENTITY
ROTOR_ENIGMAM4_1 = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
ROTOR_ENIGMAM4_2 = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
ROTOR_ENIGMAM4_3 = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
ROTOR_ENIGMAM4_4 = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
ROTOR_ENIGMAM4_5 = "VZBRGITYUPSDNHLXAWMJQOFECK"
ROTOR_ENIGMAM4_6 = "JPGVOUMFYQBENHZRDKASXLICTW"
ROTOR_ENIGMAM4_7 = "NZJHGRCXMYSWBOUFAIVLPEKQDT"
ROTOR_ENIGMAM4_8 = "FKQHTLXOCBJSPDZRAMEWNIUYGV"
GREEK_ENIGMAM4_BETA = "LEYJVCNIXWPBQMDRTAKZGFUHOS"
GREEK_ENIGMAM4_GAMMA = "FSOKANUERHMBTIYCWLQPZXVGJD"

REFLECTOR_ENIGMAM4_UKW_B = "ENKQAUYWJICOPBLMDXZVFTHRGS"
REFLECTOR_ENIGMAM4_UKW_C = "RDOBJNTKVEHMLFCWZAXGYIPSUQ"
