ROTOR_IDENTITY = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

# Entry wheel (same for all known Enigma models)
ETW = ROTOR_IDENTITY

# Rotors I-V were used in Enigma I and M4.
# Rotors VI-VIII and the Greek wheels were added for the M4 (Navy).
ROTOR_I     = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
ROTOR_II    = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
ROTOR_III   = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
ROTOR_IV    = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
ROTOR_V     = "VZBRGITYUPSDNHLXAWMJQOFECK"
ROTOR_VI    = "JPGVOUMFYQBENHZRDKASXLICTW"
ROTOR_VII   = "NZJHGRCXMYSWBOUFAIVLPEKQDT"
ROTOR_VIII  = "FKQHTLXOCBJSPDZRAMEWNIUYGV"

# Greek wheels occupy the 4th (leftmost) slot in the M4. They do not rotate.
GREEK_BETA  = "LEYJVCNIXWPBQMDRTAKZGFUHOS"
GREEK_GAMMA = "FSOKANUERHMBTIYCWLQPZXVGJD"

# Turnover positions: the letter visible in the window when the next rotor steps.
# Rotors VI, VII, and VIII have two notches.
TURNOVER_I     = ["Q"]
TURNOVER_II    = ["E"]
TURNOVER_III   = ["V"]
TURNOVER_IV    = ["J"]
TURNOVER_V     = ["Z"]
TURNOVER_VI    = ["Z", "M"]
TURNOVER_VII   = ["Z", "M"]
TURNOVER_VIII  = ["Z", "M"]

# Reflectors for Enigma I
REFLECTOR_UKW_A = "EJMZALYXVBWFCRQUONTSPIKHGD"
REFLECTOR_UKW_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"
REFLECTOR_UKW_C = "FVPJIAOYEDRZXWGCTKUQSBNMHL"

# The M4 used physically thinner versions of UKW-B and UKW-C to make room for
# the 4th rotor. Same names historically, but different wiring.
REFLECTOR_UKW_B_M4 = "ENKQAUYWJICOPBLMDXZVFTHRGS"
REFLECTOR_UKW_C_M4 = "RDOBJNTKVEHMLFCWZAXGYIPSUQ"

# Rotors available per machine model
ENIGMA_I_ROTORS  = [ROTOR_I, ROTOR_II, ROTOR_III, ROTOR_IV, ROTOR_V]
ENIGMA_M4_ROTORS = [ROTOR_I, ROTOR_II, ROTOR_III, ROTOR_IV, ROTOR_V,
                    ROTOR_VI, ROTOR_VII, ROTOR_VIII]
